config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'messages#index'
  resources :messages, only: [:create, :new, :index, :destroy]
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, class_name: 'User'
	has_many :recipients
	has_many :users, :through => :recipients

	validates :sender_id, presence: true
	validates :body, presence: true

	def user_tokens=(ids)
	    self.user_ids = ids
	end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
	belongs_to :message
	belongs_to :user

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	 has_many :messages, foreign_key: :sender_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!

	def index
		@messages = Recipient.where(:user_id => current_user.id).order('created_at DESC')
	end

	def new
		@message = Message.new
		@recipients = User.all
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			flash[:success] = 'Message sent!'
			redirect_to root_path
		else
			falsh[:alert]='Message not sent'
			render 'new'
		end
	end

	def destroy
		@message.destroy
		redirect_to root_path
	end

	private

	def message_params
		params.require(:message).permit(:body, :sender_id, user_tokens: [])
	end
	
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def root

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <div class="logo"><%= link_to 'Snap Message', root_path %></div>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">Menu</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "New", new_message_path %></li>
          <li class="nav-link"><%= link_to "Inbox", messages_path %></li>
          <li class="nav-link"><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnapMessage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |message_type, message| %>
			<div id="flash" class="flash-<%= message_type %>"><%= message %></div>
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/messages/_message.html.erb
<% @messages.each do |message| %>
  <div class="post_show">
    <div class="panel panel-default">
      <div class="panel-heading post_media">
        <% if message.message.html.present? %>
        <%= message.message.html.html_safe %>
        <% end %>
      </div>
      <div class="post-body">
        <%= message.message.content %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="name_avatar u-pull-left">
            <span class="round-image-50 name  user_avatar u-pull-left">
            
            </span>
            <span class="user_name post_name u-pull-left">
            <%= link_to message.message.sender.name, message.message.sender %>
            </span>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/_recipients.html.erb
<div id="stream">
	<%= form_for :message, url: messages_path do |f| %>
		<%= f.text_area :body,  id: "url", placeholder: "Message", class: "message_body" %>

		<div id="stream-list" class="follow-list">
			<ul>   
				<% @recipients.each do |user| %>
					<label for="user<%= user.id %>" >
						<li id="stream_item">
							<span class="list-group-item"><%= user.username %></span>
							<%= check_box_tag "message[user_tokens][]", user.id, @message.users.include?(user), id: "user#{user.id}" %>
						</li>
					</label>
					<br>
				<% end %>
			</ul>
		</div>

		<div id ="stream-footer">
			<%= f.button :submit, class: "btn btn-outline" %>
		</div>

	<% end %>
</div>

app/views/messages/index.html.erb
<div class="bigbox">
	<div class="box">
		<% @messages.each do |message| %>
		<div class="message">
			<div class="top-message">
				<li class="writting"><%= message.message.body %></li>
			</div>
			<div class="bottom-message">
				<span>From:</span><%= message.message.sender.username %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/messages/new.html.erb
<div class="form-bigbox">
	<div class="form-box">
		<%= render 'messages/recipients' %>
	</div>
</div>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/refills/_snippet.html.erb
<td class="snippet">
  <div class="copy-source-container">
    <% if language == :javascript -%>
      <a href="javascript:void(0)" class="copy-source">Copy JavaScript</a>
      <a href="javascript:void(0)" class="copy-source copy-coffee">Copy CoffeeScript</a>
    <% elsif language == :markup -%>
      <a href="javascript:void(0)" class="copy-source">Copy HTML</a>
    <% else -%>
      <a href="javascript:void(0)" class="copy-source">Copy Scss</a>
    <% end -%>
  </div>
  <pre><code class="language-<%= language %>"><%== snippet %></code></pre>
</td>

app/views/static_pages/root.html.erb
<h1>static page</h1>